---
 - name: Provision EC2
   local_action:
     module: ec2
     key_name: "{{ ec2_keypair }}"
     group_id: "{{ ec2_security_group }}"
     instance_type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
     region: "{{ ec2_region }}"
     instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}"}'
     assign_public_ip: yes
     wait: true
     exact_count: 1
     count_tag:
        Name: "{{ec2_tag_Name}}"
     volumes:
     - device_name: /dev/sda1
       device_type: gp2
       volume_size: "{{ ec2_volume_size_disk1 }}"
       delete_on_termination: true
     - device_name: /dev/sdb
       device_type: gp2
       volume_size: "{{ ec2_volume_size_disk2 }}"
       delete_on_termination: true
   register: blog-test

